---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: open-diy
spec:
  encryptedData:
    .dockerconfigjson: AgB2DAabmbV9FG0PJFbjckju80iVufBC/xzJjDMYwu1NKceuWgvcK8ZSK2fedSycxywh7/SLODY8dhcZ9CgIHpxU1ex+CRxk1XzCOfztf4um0q8XbdMSmfD0+VwU1Wp9QMGlRY2FuIwylQXOtLY6+ddlgRhnk/Y33A1Zck5eFBcj+TeVisfEHwMf5tqVhVu+4DGE8muZvcrK3u25mEIzIGQb3xh16lr1DvtNOvPLkQdBgMTw3/aQSqCI/z1vGmOqpbmxrdktKRshz87bOLiwLzp0w6Ui7mXM8VF7bUOu5noY7pkIzND7CP3gWPrWndwIQeilAHDL/mXpTT5lzMuJnz+BZ3nl1C/omCWDt0L0Sy42goofL30i6YaSPDOVTOlM/JJbkgVpgMXeVcflWuOXERJoVI7gqjuK0YzDeRpwj6zaqbAZxM+4vU9IEAQ9KH0kdvVwKt+poqPCje8ogU/N0oJ6E2PAOLNdvCkb4WnWNm9ad90DSYSPihr7GREAzNARcS0uwSGnNDKyq16A9yr11tXZcxbLSZxjFC4ay4pyXmuK7Z6n99CzedRKU/3V9te02Rv+vMVfNiBImQmlgMzekLl0yTrj/sfzZ/fDQuprs7XCn2MnbIrv4n6jCnaWp7a8Eg4ljgqHw/JUVpL86IfUECOCsWCFs/o0r9Fg1MdPQDpa71W+M6vEvlylPofJ5Sb/FQaGLlTE1j11P8wbCFWXxc+exzhaur9+7gi3xIGNmNuNyYQ6T0MVzpkKUL/qBIiz0PBn8pG+G4vCM09INJuChxrcHdxJafGy5Se9FhjJIdzhZlnq/wD6i4C+xBKo9fSr68bCgLEhB0RrnCKmT7Iy1HV2usE0Fc4IaRIT43czj/ZbiOViDNjxNSrmaAWu4XDDKOmmzfdkjInH0MqbKOFpyL9cnvQI+LAfM6554U8i3Dfkcc8q
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: open-diy
    type: kubernetes.io/dockerconfigjson
